# This file stores configurations for your Shopify app.
name = "Example App"
client_id = "459a1eb3fff01f2eaa7fd1e5d446c1cd"
application_url = "https://quickstart-9fa495fe.myshopify.com/"
embedded = true
handle = "example-app"

[auth]
redirect_urls = ["https://40d0-14-232-161-225.ngrok-free.app/auth/callback"]

[access_scopes]
scopes = "write_products, read_orders, read_products, write_products"

[webhooks]
api_version = "2024-07"



[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "https://40d0-14-232-161-225.ngrok-free.app/webhooks"
