# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8d9b9ff2491862b70d72bcc0b992d226"
name = "Tigren App"
handle = "tigren-app-31"
application_url = "https://suddenly-loud-trail-targets.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9fa495fe.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://suddenly-loud-trail-targets.trycloudflare.com/auth/callback",
  "https://suddenly-loud-trail-targets.trycloudflare.com/auth/shopify/callback",
  "https://suddenly-loud-trail-targets.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "https://pounds-transport-linked-yea.trycloudflare.com/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://pounds-transport-linked-yea.trycloudflare.com/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://pounds-transport-linked-yea.trycloudflare.com/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://pounds-transport-linked-yea.trycloudflare.com/webhooks/app/uninstalled"

[pos]
embedded = false
